baseURL = 'https://yourdomain.com/'  # ← Update this
languageCode = 'en-us'
title = 'Blog'


[params]
  bannerImage = '/images/banner_pipeline.jpeg'
  postsPerPage = 6 # Controls how many posts are displayed per page

[params.social]
  github = "your-actual-username"      
  linkedin = "your-actual-username"
  email = "your.actual@email.com"
  
[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 20

  [[menus.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 30

