baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Data Engineering Blog'


[params]
  bannerImage = '/images/banner_pipeline.jpeg'
  postsPerPage = 6 # Controls how many posts are displayed per page

[params.social]
  github = "yourusername"
  linkedin = "yourusername"
  email = "your.email@example.com"
  
[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 20

  [[menus.main]]
    name = 'Data Engineering Blog'
    url = '/posts/'
    weight = 30

